{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.0.jar",
          "url": "runelite-jshell-4.31.0.jar",
          "size": 26557,
          "sha512": "63aff1185ac799d37b142e4c6fee566ee5ae319d613eccf3b4d727021b2c55b42bc789f03daa1179fbf6862eff1f3d008f4b1bd5b15ca1830c8937611d145b40",
          "sha256": "ed0b1661621935dd4c40833934b9d94f5f08756834ffa5f48a7cb8db33b531fb",
          "sha1": "b78ec9d0239c06425ce81d6da60bf6d573e5748e",
          "md5": "16125fdbe2c84b9f4e067e567eb944e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.0.jar",
          "url": "runelite-jshell-4.31.0.jar",
          "size": 26557,
          "sha512": "63aff1185ac799d37b142e4c6fee566ee5ae319d613eccf3b4d727021b2c55b42bc789f03daa1179fbf6862eff1f3d008f4b1bd5b15ca1830c8937611d145b40",
          "sha256": "ed0b1661621935dd4c40833934b9d94f5f08756834ffa5f48a7cb8db33b531fb",
          "sha1": "b78ec9d0239c06425ce81d6da60bf6d573e5748e",
          "md5": "16125fdbe2c84b9f4e067e567eb944e1"
        }
      ]
    }
  ]
}
