{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99205,
          "sha512": "b06e41e9f49d5b5d435426278d4e21f37d481717b83d32e3bd5074750e5d6ecd610a885560588cf8e5dac0b19a66a6ef82f6946c4335a29040c12d68875d1c14",
          "sha256": "3a0040403f886385c8a6d8150f68ab51ad7ec19e7e8b4500cbb29d63033d347d",
          "sha1": "5553428bf6972f57559aeb4a8e157ccde48edbae",
          "md5": "cd203c5db7fe9fcb9b7daf330d9bff50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99205,
          "sha512": "b06e41e9f49d5b5d435426278d4e21f37d481717b83d32e3bd5074750e5d6ecd610a885560588cf8e5dac0b19a66a6ef82f6946c4335a29040c12d68875d1c14",
          "sha256": "3a0040403f886385c8a6d8150f68ab51ad7ec19e7e8b4500cbb29d63033d347d",
          "sha1": "5553428bf6972f57559aeb4a8e157ccde48edbae",
          "md5": "cd203c5db7fe9fcb9b7daf330d9bff50"
        }
      ]
    }
  ]
}
