{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.3.jar",
          "url": "injector-plugin-2.0.3.jar",
          "size": 123659,
          "sha512": "d6cfc854c525333a68d98f20d9a967685311bd92efbc91132fb98fda77d48304d4fc626ec835c1c984c614548a8b76bf5611049ccab2ffaae0e582269c10129a",
          "sha256": "69ab903d7ceee6a555e2f7c4ad3a9dfda62b4c6b7fec0e3dcff41e68f705166d",
          "sha1": "6bb4c1ad2801aa2eb2bf8bf93bf11fe9715623d5",
          "md5": "6e54b343d1c6e5f78e7ef4f08f0ed551"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.3.jar",
          "url": "injector-plugin-2.0.3.jar",
          "size": 123659,
          "sha512": "d6cfc854c525333a68d98f20d9a967685311bd92efbc91132fb98fda77d48304d4fc626ec835c1c984c614548a8b76bf5611049ccab2ffaae0e582269c10129a",
          "sha256": "69ab903d7ceee6a555e2f7c4ad3a9dfda62b4c6b7fec0e3dcff41e68f705166d",
          "sha1": "6bb4c1ad2801aa2eb2bf8bf93bf11fe9715623d5",
          "md5": "6e54b343d1c6e5f78e7ef4f08f0ed551"
        }
      ]
    }
  ]
}
