{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.10.0.jar",
          "url": "runelite-api-4.10.0.jar",
          "size": 1292571,
          "sha512": "78a9a120758335f1576a780c0275076dc3e6d638e0b8f96559dc5b2380921f3be88eb973a36c97c259915f9419535195c9f6d0d3438852762666cb95dd807980",
          "sha256": "bba1a69571fed94057f3911c1bfc6e46e0913d1df12997420dd49ac29ec2a529",
          "sha1": "07facd9a4b17fd2b8a74da5d72d4cb4773d726c2",
          "md5": "6120a85f6c3c498d28a81f1e7643ea9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.10.0.jar",
          "url": "runelite-api-4.10.0.jar",
          "size": 1292571,
          "sha512": "78a9a120758335f1576a780c0275076dc3e6d638e0b8f96559dc5b2380921f3be88eb973a36c97c259915f9419535195c9f6d0d3438852762666cb95dd807980",
          "sha256": "bba1a69571fed94057f3911c1bfc6e46e0913d1df12997420dd49ac29ec2a529",
          "sha1": "07facd9a4b17fd2b8a74da5d72d4cb4773d726c2",
          "md5": "6120a85f6c3c498d28a81f1e7643ea9c"
        }
      ]
    }
  ]
}
