{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99214,
          "sha512": "4286c4b7208158623c8b6dd378dd2dbdbf23dea3dbdc22be346cafb234675da0668114fdf87543c5b35f1438e6a131ee8379a61ae44aafad4a9a7ff3f066fe70",
          "sha256": "acf18e1330a40d921caa2e5dc421ca20cc692828b00366a06001acdf161c6cb4",
          "sha1": "ef83e7522afd85593c66a707884c76375974cfe6",
          "md5": "57874068b2c13d6a785e619cc8feeacf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99214,
          "sha512": "4286c4b7208158623c8b6dd378dd2dbdbf23dea3dbdc22be346cafb234675da0668114fdf87543c5b35f1438e6a131ee8379a61ae44aafad4a9a7ff3f066fe70",
          "sha256": "acf18e1330a40d921caa2e5dc421ca20cc692828b00366a06001acdf161c6cb4",
          "sha1": "ef83e7522afd85593c66a707884c76375974cfe6",
          "md5": "57874068b2c13d6a785e619cc8feeacf"
        }
      ]
    }
  ]
}
