{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359500,
          "sha512": "de2546fc524b92b2dfacfbdb5a77fbe236ac9007b0c7e3519dcd1a1129380c94cdad66ed7f45b490a926f079e01c762219fb0f7001c628c7d694e1c87da3d358",
          "sha256": "fb4e99f7151814cb03cd4404570f0d34b1f18f845767d83fe59c05fdbb45ff62",
          "sha1": "cbbe341978c15e0ad861e577f4136fca56b3b4fa",
          "md5": "885f825f3a83193408ec2a22c056fe43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359500,
          "sha512": "de2546fc524b92b2dfacfbdb5a77fbe236ac9007b0c7e3519dcd1a1129380c94cdad66ed7f45b490a926f079e01c762219fb0f7001c628c7d694e1c87da3d358",
          "sha256": "fb4e99f7151814cb03cd4404570f0d34b1f18f845767d83fe59c05fdbb45ff62",
          "sha1": "cbbe341978c15e0ad861e577f4136fca56b3b4fa",
          "md5": "885f825f3a83193408ec2a22c056fe43"
        }
      ]
    }
  ]
}
