{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99207,
          "sha512": "73997e1059910698fc783d207fc17df3f748177e6fdcf88abba44d9f734341415729f8c707f20aac8940b6381dd38587b9a333c6ae79045da9d12f867b34cc73",
          "sha256": "81f038061427a6bb4c4bcee9cb1325dd5caaafc6e96fb5b59398d1b95204ff26",
          "sha1": "9deec5f286a234184fa7b41624329c2e6c5dd2d2",
          "md5": "78f36095dad3e891ec02de9133c42dda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99207,
          "sha512": "73997e1059910698fc783d207fc17df3f748177e6fdcf88abba44d9f734341415729f8c707f20aac8940b6381dd38587b9a333c6ae79045da9d12f867b34cc73",
          "sha256": "81f038061427a6bb4c4bcee9cb1325dd5caaafc6e96fb5b59398d1b95204ff26",
          "sha1": "9deec5f286a234184fa7b41624329c2e6c5dd2d2",
          "md5": "78f36095dad3e891ec02de9133c42dda"
        }
      ]
    }
  ]
}
