{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.10.0.jar",
          "url": "runelite-api-4.10.0.jar",
          "size": 1288895,
          "sha512": "4640973e5c4d03c5ce4090283318de4a6b221b591ac02155d434edaf4abe3af8abb41536d01de999c14544f0e833e9d3c3351d6df1fcd90cd15b75f07ae61924",
          "sha256": "71df432a08113bf144e0654623fb39dc527dc21ffaa506d3e38428f82d9e7889",
          "sha1": "71a22b2f069f35f453d62fecad2fd3a09b691006",
          "md5": "d3d07e6b6cb6e8c2a40d4d1e099e8575"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.10.0.jar",
          "url": "runelite-api-4.10.0.jar",
          "size": 1288895,
          "sha512": "4640973e5c4d03c5ce4090283318de4a6b221b591ac02155d434edaf4abe3af8abb41536d01de999c14544f0e833e9d3c3351d6df1fcd90cd15b75f07ae61924",
          "sha256": "71df432a08113bf144e0654623fb39dc527dc21ffaa506d3e38428f82d9e7889",
          "sha1": "71a22b2f069f35f453d62fecad2fd3a09b691006",
          "md5": "d3d07e6b6cb6e8c2a40d4d1e099e8575"
        }
      ]
    }
  ]
}
