{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346888,
          "sha512": "3f081fa64c63e6b74e5acabd4e4b9d204df58299c2d7ce75285424766625849ef0eb41a8fd800922facb9cf41ad1b72b9b1a58d1f057f237e7ba44835488aaad",
          "sha256": "b7262a19a6967245e92337c07ebe5e783c31170bdfc61178b7a8f5dc7ad085d9",
          "sha1": "009b06aacaa8ed469b354d70f67bba6590a1b262",
          "md5": "e9ab06ba431c0aa6554377062d374ccb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346888,
          "sha512": "3f081fa64c63e6b74e5acabd4e4b9d204df58299c2d7ce75285424766625849ef0eb41a8fd800922facb9cf41ad1b72b9b1a58d1f057f237e7ba44835488aaad",
          "sha256": "b7262a19a6967245e92337c07ebe5e783c31170bdfc61178b7a8f5dc7ad085d9",
          "sha1": "009b06aacaa8ed469b354d70f67bba6590a1b262",
          "md5": "e9ab06ba431c0aa6554377062d374ccb"
        }
      ]
    }
  ]
}
