{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "2208a4c5d232cb209af02fc88029b42654867b08298e5502c0d6f7115eca04f909a452c997766d0fcb5d6d96aa646abe3ade9ed55b2ca0992f7dc40bb7af8dac",
          "sha256": "e7c0659458e28f01099b0668a61b1019bc9a5a27ffdbf140967fc57ea162fd8f",
          "sha1": "80554d1fb51d784a0c86078c68958efa108256cb",
          "md5": "e93c85c5ecf153f4378b037d9c1d67b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "2208a4c5d232cb209af02fc88029b42654867b08298e5502c0d6f7115eca04f909a452c997766d0fcb5d6d96aa646abe3ade9ed55b2ca0992f7dc40bb7af8dac",
          "sha256": "e7c0659458e28f01099b0668a61b1019bc9a5a27ffdbf140967fc57ea162fd8f",
          "sha1": "80554d1fb51d784a0c86078c68958efa108256cb",
          "md5": "e93c85c5ecf153f4378b037d9c1d67b8"
        }
      ]
    }
  ]
}
