{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injector-1.0.jar",
          "url": "injector-1.0.jar",
          "size": 112574,
          "sha512": "c110ca24fb6987b6e50d7b97ded6eeae868cc8f7a3eab96738e751f9f2fb859fde174478cc32a736ce936d5a2c3a47eba01952225888aeb84685cb317ff74591",
          "sha256": "33436a0f5ced7b585c7acc8e38c786b4354c41e57f0b34b2371a4e92cf14574d",
          "sha1": "3a483e79981b75379eca32820a39f78f2869ba3b",
          "md5": "d7fb5cf2a80afa47b271004107e9bbc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-client",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-mixins",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "injector-1.0.jar",
          "url": "injector-1.0.jar",
          "size": 112574,
          "sha512": "c110ca24fb6987b6e50d7b97ded6eeae868cc8f7a3eab96738e751f9f2fb859fde174478cc32a736ce936d5a2c3a47eba01952225888aeb84685cb317ff74591",
          "sha256": "33436a0f5ced7b585c7acc8e38c786b4354c41e57f0b34b2371a4e92cf14574d",
          "sha1": "3a483e79981b75379eca32820a39f78f2869ba3b",
          "md5": "d7fb5cf2a80afa47b271004107e9bbc0"
        }
      ]
    }
  ]
}
