{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357159,
          "sha512": "587891408b7796b42b2bbf823e122d1e876472af89d825ab318f191eeaf959d60d8c3700072d9a5374e517e0bb74e37a30a8db4f6302cc602bf8083161345884",
          "sha256": "ef68ba204217d534337d82be8fe62e0bfac586baeff7198fd7663309a0bd2c58",
          "sha1": "41bda85885132ad32fb1dfa6a924d7ddc8f0d552",
          "md5": "b8cee8c29a60dacda875daad34ac700c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357159,
          "sha512": "587891408b7796b42b2bbf823e122d1e876472af89d825ab318f191eeaf959d60d8c3700072d9a5374e517e0bb74e37a30a8db4f6302cc602bf8083161345884",
          "sha256": "ef68ba204217d534337d82be8fe62e0bfac586baeff7198fd7663309a0bd2c58",
          "sha1": "41bda85885132ad32fb1dfa6a924d7ddc8f0d552",
          "md5": "b8cee8c29a60dacda875daad34ac700c"
        }
      ]
    }
  ]
}
