{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.1.jar",
          "url": "runescape-api-4.31.1.jar",
          "size": 150296,
          "sha512": "531d1ed9446903b06e52325c36de00ce5d055f5672902409e28626a8745bdcfe27f2d7ca4ddefba1b61ac8335bb62a0063452dbfdc2e21db071790b57d1ba3ef",
          "sha256": "170a89c830e2e803ca062aedca2a5d0aa741749575da4dc519306cdb4f90014a",
          "sha1": "24fed02ddb07f7108b847a31497c25078fb8b710",
          "md5": "e41171c89421564d10bf728aa0add2dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.1.jar",
          "url": "runescape-api-4.31.1.jar",
          "size": 150296,
          "sha512": "531d1ed9446903b06e52325c36de00ce5d055f5672902409e28626a8745bdcfe27f2d7ca4ddefba1b61ac8335bb62a0063452dbfdc2e21db071790b57d1ba3ef",
          "sha256": "170a89c830e2e803ca062aedca2a5d0aa741749575da4dc519306cdb4f90014a",
          "sha1": "24fed02ddb07f7108b847a31497c25078fb8b710",
          "md5": "e41171c89421564d10bf728aa0add2dc"
        }
      ]
    }
  ]
}
