{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1361948,
          "sha512": "d3fb8e7ef9d7744543f57e9bc1028896b20196d2b31d56863cd0f4edc8b4a45e389e19f93c7d7dfd9a8fadcbc250561fbf70616f801162cd79bfed60aacd0a6e",
          "sha256": "3f9aeae7cce55e9929954c85cc5d88699f078148d431027f0fce28178accdf5f",
          "sha1": "aef5af0d90c3babf5c9ad1b8215db7e1f7020359",
          "md5": "99a51457159f6ef246661ba6710e2d88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1361948,
          "sha512": "d3fb8e7ef9d7744543f57e9bc1028896b20196d2b31d56863cd0f4edc8b4a45e389e19f93c7d7dfd9a8fadcbc250561fbf70616f801162cd79bfed60aacd0a6e",
          "sha256": "3f9aeae7cce55e9929954c85cc5d88699f078148d431027f0fce28178accdf5f",
          "sha1": "aef5af0d90c3babf5c9ad1b8215db7e1f7020359",
          "md5": "99a51457159f6ef246661ba6710e2d88"
        }
      ]
    }
  ]
}
