{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.0.jar",
          "url": "runelite-api-4.26.0.jar",
          "size": 1357159,
          "sha512": "0b68b1bf590bb0a5b9e22283cb8b2c9dea051313b4b38c37ce6422ed5bc8fe017ab52c8cddeb430d6bd2ed6b036b1b040c57e6664b6c0dec647700dc4e3c89c3",
          "sha256": "1789b83971f78da1845de41ee3d87624a5cb4e8eb34d657dd79aeaa517fb754d",
          "sha1": "e032fcd29767d70e965ca65e9ae3af63880291c4",
          "md5": "8da7eadc5d1ab3e8e0ba127fff0fbcd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.0.jar",
          "url": "runelite-api-4.26.0.jar",
          "size": 1357159,
          "sha512": "0b68b1bf590bb0a5b9e22283cb8b2c9dea051313b4b38c37ce6422ed5bc8fe017ab52c8cddeb430d6bd2ed6b036b1b040c57e6664b6c0dec647700dc4e3c89c3",
          "sha256": "1789b83971f78da1845de41ee3d87624a5cb4e8eb34d657dd79aeaa517fb754d",
          "sha1": "e032fcd29767d70e965ca65e9ae3af63880291c4",
          "md5": "8da7eadc5d1ab3e8e0ba127fff0fbcd3"
        }
      ]
    }
  ]
}
