{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "0294fda104ab09075be65ccc4e5390cf21e7fe9faf7e211d88d0e7023983241b4f07b3f1f08e7181c89a91c1b2f2cf67a1556ae8e1191c9c61c63997e82408f0",
          "sha256": "a58ba02c967aedbe870578b8550000d9bd35461c925511543b414a94f3e25d18",
          "sha1": "ec1ae8cca92fccfbb60cf9b08fff397d5eebac07",
          "md5": "dee2bc70b092ec5fee2a6d934c7c314b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "0294fda104ab09075be65ccc4e5390cf21e7fe9faf7e211d88d0e7023983241b4f07b3f1f08e7181c89a91c1b2f2cf67a1556ae8e1191c9c61c63997e82408f0",
          "sha256": "a58ba02c967aedbe870578b8550000d9bd35461c925511543b414a94f3e25d18",
          "sha1": "ec1ae8cca92fccfbb60cf9b08fff397d5eebac07",
          "md5": "dee2bc70b092ec5fee2a6d934c7c314b"
        }
      ]
    }
  ]
}
