{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.30.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.30.0.jar",
          "url": "runescape-api-4.30.0.jar",
          "size": 150296,
          "sha512": "125dc895504741bac6ad3837a0dbcfe1a88d2d4196ce645d37815d127fd71b4aa97109e9af123f20f1d2534fbc18ae720dc6506457f2f25afd28a76f88d833fe",
          "sha256": "a2fb4722198922d104014eeb41a4452ebc633d860b7b3d823ca0ae1b5781bd2f",
          "sha1": "632f4586035c133950fc90584f3f241d74ac3115",
          "md5": "f3f5dac884b95aac1402dbe596505d3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.30.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.30.0.jar",
          "url": "runescape-api-4.30.0.jar",
          "size": 150296,
          "sha512": "125dc895504741bac6ad3837a0dbcfe1a88d2d4196ce645d37815d127fd71b4aa97109e9af123f20f1d2534fbc18ae720dc6506457f2f25afd28a76f88d833fe",
          "sha256": "a2fb4722198922d104014eeb41a4452ebc633d860b7b3d823ca0ae1b5781bd2f",
          "sha1": "632f4586035c133950fc90584f3f241d74ac3115",
          "md5": "f3f5dac884b95aac1402dbe596505d3a"
        }
      ]
    }
  ]
}
