{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "d1e2f5f95b6e5e9ea0da5aaa58fa7da7ce9bcc3b2ab4d326bde5eb09f744562bac58e376f64473746bdf642fec62bda33286586800f5fc2aeed0e4f923fcc669",
          "sha256": "4f476022ab530232ea8dda5795df51a428170c2013b930a7e465124b711c0ce1",
          "sha1": "7087890d4010c376cf4a7b9cbac211bebfaf2a09",
          "md5": "0b1ab6a977cfe6371400fcb7de74cbee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "d1e2f5f95b6e5e9ea0da5aaa58fa7da7ce9bcc3b2ab4d326bde5eb09f744562bac58e376f64473746bdf642fec62bda33286586800f5fc2aeed0e4f923fcc669",
          "sha256": "4f476022ab530232ea8dda5795df51a428170c2013b930a7e465124b711c0ce1",
          "sha1": "7087890d4010c376cf4a7b9cbac211bebfaf2a09",
          "md5": "0b1ab6a977cfe6371400fcb7de74cbee"
        }
      ]
    }
  ]
}
