{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "w4dfoxscvfcaxh6ndkzz7auvje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.5.3.jar",
          "url": "injected-client-3.5.3.jar",
          "size": 2236273,
          "sha512": "47bee553747851dce253360234efa552e1247c04cd9e954e04ab88691cdec86cc49cb4a9534ed55ac0dbf5c4c726a9992719dcbc409880c191b386a991c9de22",
          "sha256": "6e7066d4edf7388efc400eaf9aeae7cdbc43c9ecf774ee6fdab5a0e559587943",
          "sha1": "9daba2e7e9d03938fd394dd65f6114078c566622",
          "md5": "bcfd06927d7f9b7d050ff4b4bed23f15"
        }
      ]
    }
  ]
}
