{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 161226,
          "sha512": "c8cf2a89bc0addd4a6898a2a5567164898cbf9413846dfc966ec7b2efdb53009a32dc2939d11f8a76b007ae69be5204e11218b63dc15752ea3d076031ee1b6ea",
          "sha256": "0db9e86954b6f98eb2d776b09abb6f81d81caa842b3eebb1ff1d18fdb31f0bf1",
          "sha1": "9af5b3844775782ecb8d2ac32bf95605c8fe9875",
          "md5": "ad1ad41cfbdac8e77396b2647ddc5ae3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 161226,
          "sha512": "c8cf2a89bc0addd4a6898a2a5567164898cbf9413846dfc966ec7b2efdb53009a32dc2939d11f8a76b007ae69be5204e11218b63dc15752ea3d076031ee1b6ea",
          "sha256": "0db9e86954b6f98eb2d776b09abb6f81d81caa842b3eebb1ff1d18fdb31f0bf1",
          "sha1": "9af5b3844775782ecb8d2ac32bf95605c8fe9875",
          "md5": "ad1ad41cfbdac8e77396b2647ddc5ae3"
        }
      ]
    }
  ]
}
