{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.10.0.jar",
          "url": "runescape-api-4.10.0.jar",
          "size": 111609,
          "sha512": "c2a1cad63a32d00718acf6add236a47e5bc19559c61b136944c381f82bbf1cdf57e34a30ada586f29d207ba7912eaec48937e3c19c0381a6fb0fc9420526b03f",
          "sha256": "679d69993f9f7b607db55b32cc7b3e9a12b7f95b2d94f6a090a8150852d1d9fd",
          "sha1": "2cc280721f13260b434b942a08192b9a7a2500fd",
          "md5": "679d6c16a051a94bc07938e3277fd1dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.10.0.jar",
          "url": "runescape-api-4.10.0.jar",
          "size": 111609,
          "sha512": "c2a1cad63a32d00718acf6add236a47e5bc19559c61b136944c381f82bbf1cdf57e34a30ada586f29d207ba7912eaec48937e3c19c0381a6fb0fc9420526b03f",
          "sha256": "679d69993f9f7b607db55b32cc7b3e9a12b7f95b2d94f6a090a8150852d1d9fd",
          "sha1": "2cc280721f13260b434b942a08192b9a7a2500fd",
          "md5": "679d6c16a051a94bc07938e3277fd1dd"
        }
      ]
    }
  ]
}
